app:
  image: krbh0717/petclinic:v5
  ports:
  - "8080:8080"
  environment:
  - SPRING_PROFILES_ACTIVE=mysql
  links: 
  - db:db 

db: 
  image: mysql:5.7
  ports:
  - "3306:3306"
  environment:
  - MYSQL_ALLOW_EMPTY_PASSWORD=true
  - MYSQL_USER=petclinic
  - MYSQL_PASSWORD=petclinic
  - MYSQL_DATABASE=petclinic
 
