version: "3.8"
networks:
  petclinic:
    driver: bridge

services:
  app:
    image: krbh0717/petclinic:v5
    ports:
    - "8080:8080"
    environment:
    - SPRING_PROFILES_ACTIVE=mysql
    networks: 
    - petclinic
    depends_on:
    - db

  db: 
    image: mysql:5.7
    ports:
    - "3306:3306"
    environment:
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=petclinic
    - MYSQL_PASSWORD=petclinic
    - MYSQL_DATABASE=petclinic
    networks:
    - petclinic
